# Generated by Django 4.1 on 2022-08-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='last_quote',
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
