# Generated by Django 4.1 on 2022-08-12 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_uid_customuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id',
            new_name='uid',
        ),
    ]
