# Generated by Django 4.1 on 2022-08-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='last_notification',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
